### ISSUE TITLE
KeyError exception in Requester.wrap(self, method):

### ISSUE THREAD

**Issue by akochkarev** [akshay-movieverse/yandex-api#1]
My code:
```
...
        disk = yadisk_api.YandexDisk("<my_token>")
        info = disk.get_disk_info()
...
```
Result:

Traceback (most recent call last):
  File "c:\work\py\myapp\tests\test_uploader.py", line 18, in <module>
    yd.uploadFile('big.mkv', '/+test/big.mkv')
  File "c:\work\py\myapp\myapp\uploader\yadiskuploader.py", line 50, in uploadFile
    info = disk.get_disk_info()
  File "C:\Users\alex\envs\my_project\lib\site-packages\yadisk_api\client.py", line 26, in get_disk_info
    return self._requester.get(url='disk/').json()
  File "C:\Users\alex\envs\my_project\lib\site-packages\yadisk_api\requester.py", line 43, in get
    return self.wrap(requests.get)(url=url, params=params, **kwargs)
  File "C:\Users\alex\envs\my_project\lib\site-packages\yadisk_api\requester.py", line 69, in wrap
    }[method]
KeyError: <function get at 0x021E79C0>

**Comment by gr3yknigh1** [comment]
@akochkarev Hi! I faced the same issue. The thing is on PyPi uploaded the older version of this project, and if you try to clone this repo and install with pip this error will disappear.

**Comment by gr3yknigh1** [comment]
I was wrong. Package was renamed from `yadisk-api` to `yandex-api`. Simply install `yandex-api` and errors will disappear
